os: osx
osx_image: xcode7.3

before_install:
  - brew install curl
  - wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a-osx.pkg -target /
  - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
  - cp Config/Configuration-Sample.swift Sources/Configuration.swift
  
script:
    - swift build
